networks:
  prod:
    name: prod

services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - prod
    restart: unless-stopped
    environment:
      - POSTGRES_USER="${SPRING_DATASOURCE_USERNAME}"
      - POSTGRES_PASSWORD="${SPRING_DATASOURCE_PASSWORD}"
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - backend
      - frontend
    networks:
      - prod
  backend:
    build:
      context: ./backend
    networks:
      - prod
  frontend:
    build:
      context: ./frontend
    networks:
      - prod
