name: Deploy

on:
  workflow_dispatch

env:
  SERVER_HOST: 90.156.158.203
  SERVER_USER: root

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: test
        run: echo "${{ secrets.SSH_KEY }}"
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Run script on server
        run: |
          ssh -o StrictHostKeyChecking=no root@90.156.158.203 "
            cd Electronic-Medicine;
            git config --global --add safe.directory /root/Electronic-Medicine;
            git pull;
            docker-compose up --build -d
          "
#

#  runs-on: ubuntu-latest
#  steps:
#    - name: Set up SSH
#      run: |
#        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
#        chmod 600 ~/.ssh/id_rsa
#        ssh-keyscan -H 90.156.158.203 >> ~/.ssh/known_hosts
#    - name: Connect to SSH Server
#      run: |
#        ssh ${{ secrets.HOST }}
#    - name: change directory
#      run: cd Electronic-Medicine
#    - name: github pull
#      run: git pull
#    - name: build project to cloud
#      run:

