name: Deploy

on:
  workflow_dispatch

env:
  SERVER_HOST: 90.156.158.203
  SERVER_USER: root
  SERVER_PATH: /root/Electronic-Medicine

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ env.SERVER_HOST }}" >> ~/.ssh/known_hosts

      - name: Run script on server
        run: |
          ssh -i ~/.ssh/id_rsa "${{ secrets.SSH_HOST }}" git pull
          ssh -i ~/.ssh/id_rsa "${{ secrets.SSH_HOST }}" cd Electronic-Medicine
          ssh -i ~/.ssh/id_rsa "${{ secrets.SSH_HOST }}" docker compose up --build -d
        



#  runs-on: ubuntu-latest
#  steps:
#    - name: Set up SSH
#      run: |
#        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
#        chmod 600 ~/.ssh/id_rsa
#        ssh-keyscan -H 90.156.158.203 >> ~/.ssh/known_hosts
#    - name: Connect to SSH Server
#      run: |
#        ssh ${{ secrets.HOST }}
#    - name: change directory
#      run: cd Electronic-Medicine
#    - name: github pull
#      run: git pull
#    - name: build project to cloud
#      run: docker compose up --build -d