name: Deploy

on:
  workflow_dispatch

env:
  SERVER_HOST: 89.108.77.14
  SERVER_USER: root
  SERVER_PATH: /root/Electronic-Medicine

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Install ssh key
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: "${{ secrets.SSH_KEY }}"
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      - name: Generate auth hosts
        run: ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts

      # Deploy
      - run: rsync --archive --compress --progress . ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH }}



#  runs-on: ubuntu-latest
#  steps:
#    - name: Set up SSH
#      run: |
#        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
#        chmod 600 ~/.ssh/id_rsa
#        ssh-keyscan -H 90.156.158.203 >> ~/.ssh/known_hosts
#    - name: Connect to SSH Server
#      run: |
#        ssh ${{ secrets.HOST }}
#    - name: change directory
#      run: cd Electronic-Medicine
#    - name: github pull
#      run: git pull
#    - name: build project to cloud
#      run: docker compose up --build -d