name: Deploy

on:
  workflow_dispatch

env:
  SERVER_HOST: 90.156.158.203
  SERVER_USER: root

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_KEY}}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{env.SERVER_HOST}} >> ~/.ssh/known_hosts

      - name: Run script on server
        run: |
          ssh root@${{ env.SERVER_HOST }} "
          ssh -i ~/.ssh/id_ed25519 root@90.156.158.203
            cd Electronic-Medicine;
            git pull;
            docker-compose down;
            docker-compose up --build -d;
          
          while ! docker ps | grep -q 'electronic-medicine_backend_1'; do
          echo 'Waiting for the container to start...';
          sleep 5;
          done;
          "
